Repository etylizer/etylizer, pull requests merged in 2024-11, with the labels that each got.

#169 Fix includes
  src/ast_check.erl
  src/ast_transform.erl
  src/cm_check.erl
  src/cm_depgraph.erl
  src/cm_index.erl
  src/constr_collect.erl
  src/constr_error_locs.erl
  src/constr_gen.erl
  src/constr_simp.erl
  src/constr_solve.erl
  src/erlang_types/etally.erl
  src/erlang_types/sanity.hrl
  src/erlang_types/ty_rec.erl
  src/ety_main.erl
  src/fungraph.erl
  src/parse.erl
  src/parse.hrl
  src/parse_cache.erl
  src/paths.erl
  src/pretty.erl
  src/stdtypes.erl
  src/subst.erl
  src/symtab.erl
  src/test_utils.erl
  src/tmp.erl
  src/typing.erl
  src/typing.hrl
  src/typing_check.erl
  src/typing_common.erl
  src/typing_infer.erl
  src/tyutils.erl
  src/utils.erl
  test/ast_transform_test.erl
  test/cm_depgraph_tests.erl
  test/cm_recompile_tests.erl
  test/constr_gen_tests.erl
  test/fungraph_tests.erl
  test/pretty_test.erl
  test/tally_tests.erl
  test/tycheck_simple_tests.erl
  test/tycheck_tests.erl
Labels: Refactor

#170 fix for #154
  src/ast.erl
  src/ast_transform.erl
  src/ast_utils.erl
  src/cm_module_interface.erl
  src/errors.erl
  src/pp.erl
  src/pretty.erl
  src/subst.erl
  src/symtab.erl
  src/typing.erl
  src/utils.erl
  test/cm_module_interface_tests.erl
  test/pretty_test.erl
  test/tycheck_simple_tests.erl
  test_files/extract_interface/m_parametrized_types.erl
  test_files/tycheck/README.md
  test_files/tycheck/modules-bug-154/m1.erl
  test_files/tycheck/modules-bug-154/m2.erl
Labels: architecture

#172 Types refactor
  src/ast_lib.erl
  src/erlang_types/bdd.hrl
  src/erlang_types/dnf_ty_function.erl
  src/erlang_types/dnf_ty_interval.erl
  src/erlang_types/dnf_ty_list.erl
  src/erlang_types/dnf_ty_map.erl
  src/erlang_types/dnf_ty_predef.erl
  src/erlang_types/dnf_ty_tuple.erl
  src/erlang_types/dnf_var_int.erl
  src/erlang_types/dnf_var_ty_function.erl
  src/erlang_types/dnf_var_ty_interval.erl
  src/erlang_types/dnf_var_ty_predef.erl
  src/erlang_types/dnf_var_ty_tuple.erl
  src/erlang_types/ty_bool.erl
  src/erlang_types/ty_functions.erl
  src/erlang_types/ty_rec.erl
  src/erlang_types/ty_ref.erl
  src/erlang_types/ty_tuple.erl
  src/erlang_types/ty_tuples.erl
Labels: Refactor

#176 fix #155
  src/ast.erl
  src/constr_gen.erl
  src/constr_solve.erl
  src/fungraph.erl
  src/graph.erl
  src/subst.erl
  src/typing_check.erl
  src/typing_common.erl
  src/typing_infer.erl
  src/utils.erl
  test/mono_tests.erl
  test/tycheck_simple_tests.erl
  test/tycheck_tests.erl
  test/typing_tests.erl
  test_files/tycheck/range1.erl
  test_files/tycheck/range2.erl
  test_files/tycheck/range3.erl
  test_files/tycheck_simple/alias.erl
Labels: bug, constraint system

#185 Fixed call to bash to enable more environments
  ety
Labels: CLI
