Repository etylizer/etylizer, pull requests merged in 2024-10, with the labels that each got.

#129 Fix unary type specification
  src/stdtypes.erl
  test_files/tycheck_simple.erl
Labels: bug, constraint system

#119 Unsound memoization
  src/erlang_types/dnf_ty_function.erl
  src/erlang_types/dnf_ty_list.erl
  src/erlang_types/dnf_ty_map.erl
  src/erlang_types/dnf_ty_tuple.erl
  src/erlang_types/dnf_var_ty_function.erl
  src/erlang_types/dnf_var_ty_list.erl
  src/erlang_types/dnf_var_ty_map.erl
  src/erlang_types/dnf_var_ty_tuple.erl
  test_files/tally/foo5.config
  test_files/tally/foo5_2.config
  test_files/tycheck_simple.erl
Labels: bug, Tally

#133 split tycheck_simple_tests into multiple files, run all tests
  test/tycheck_simple_tests.erl
  test_files/tycheck_simple.erl
  test_files/tycheck_simple/basic_types.erl
  test_files/tycheck_simple/blocks.erl
  test_files/tycheck_simple/case_of.erl
  test_files/tycheck_simple/conditional.erl
  test_files/tycheck_simple/exceptions.erl
  test_files/tycheck_simple/fun_local.erl
  test_files/tycheck_simple/funs_ops.erl
  test_files/tycheck_simple/intersection.erl
  test_files/tycheck_simple/lists.erl
  test_files/tycheck_simple/poly.erl
  test_files/tycheck_simple/tuples.erl
Labels: Refactor

#131 Erlang 27 support. Fixes #130.
  .github/workflows/erlang.yml
  src/ast_transform.erl
Labels: enhancement, AST

#109 Constraints for maps and records
  src/ast.erl
  src/ast_lib.erl
  src/ast_transform.erl
  src/constr_gen.erl
  src/ety_main.erl
  src/log.erl
  src/log.hrl
  src/paths.erl
  src/pretty.erl
  src/pretty_test.erl
  src/records.erl
  src/stdtypes.erl
  src/symtab.erl
  src/typing_check.erl
  src/typing_common.erl
  src/utils.erl
  test/tally_tests.erl
  test_files/ast_transform/patterns.out
  test_files/ast_transform/scope_map.out
  test_files/tycheck_simple/maps.erl
  test_files/tycheck_simple/records.erl
  test_files/tycheck_simple/records.hrl
Labels: enhancement

#116 User-defined types and recursive types
  src/ast.erl
  src/ast_lib.erl
  src/ast_utils.erl
  src/erlang_types/bdd.hrl
  src/erlang_types/bdd_bool.erl
  src/erlang_types/dnf_ty_function.erl
  src/erlang_types/dnf_ty_list.erl
  src/erlang_types/dnf_ty_map.erl
  src/erlang_types/dnf_ty_tuple.erl
  src/erlang_types/dnf_var_int.erl
  src/erlang_types/dnf_var_predef.erl
  src/erlang_types/dnf_var_ty_atom.erl
  src/erlang_types/dnf_var_ty_function.erl
  src/erlang_types/dnf_var_ty_list.erl
  src/erlang_types/dnf_var_ty_map.erl
  src/erlang_types/dnf_var_ty_tuple.erl
  src/erlang_types/etally.erl
  src/erlang_types/ty_atom.erl
  src/erlang_types/ty_function.erl
  src/erlang_types/ty_interval.erl
  src/erlang_types/ty_list.erl
  src/erlang_types/ty_map.erl
  src/erlang_types/ty_predef.erl
  src/erlang_types/ty_rec.erl
  src/erlang_types/ty_ref.erl
  src/erlang_types/ty_tuple.erl
  src/erlang_types/ty_variable.erl
  src/pretty.erl
  src/stdtypes.erl
  src/subty.erl
  src/tally.erl
  src/test_utils.erl
  test/pretty_tests.erl
  test/tally_tests.erl
  test/tycheck_simple_tests.erl
  test_files/tally/user_07.config
  test_files/tycheck_simple/user.erl
Labels: enhancement, AST

#136 Refine pre-defined type of andalso and orelse
  src/stdtypes.erl
  test_files/tycheck_simple/funs_ops.erl
Labels: enhancement

#92 Introduce caching for erlang_ty_to_ast to prevent unnecessary transformations
  src/ast_lib.erl
Labels: enhancement, Community, performance

#147 fix soundness bug with maps #139
  src/constr_gen.erl
  src/stdtypes.erl
  test_files/tycheck_simple/maps.erl
Labels: bug, constraint system

#150 Fix typo
  README.md
Labels: documentation

#156 improvements
  src/ast.erl
  src/ast_erl.erl
  src/ast_transform.erl
  src/cm_check.erl
  src/constr_gen.erl
  src/constr_solve.erl
  src/errors.erl
  src/ety_main.erl
  src/ety_main.hrl
  src/paths.erl
  src/typing_check.erl
  src/utils.erl
  test_files/tycheck_simple/comprehension.erl
  test_files/tycheck_simple/records.erl
Labels: enhancement, AST

#158 Fix co-recursion for subtyping and tallying
  src/erlang_types/constraint_set.erl
  src/erlang_types/dnf_ty_function.erl
  src/erlang_types/dnf_ty_list.erl
  src/erlang_types/dnf_ty_map.erl
  src/erlang_types/dnf_ty_tuple.erl
  src/erlang_types/dnf_var_int.erl
  src/erlang_types/dnf_var_predef.erl
  src/erlang_types/dnf_var_ty_atom.erl
  src/erlang_types/dnf_var_ty_function.erl
  src/erlang_types/dnf_var_ty_list.erl
  src/erlang_types/dnf_var_ty_map.erl
  src/erlang_types/dnf_var_ty_tuple.erl
  src/erlang_types/etally.erl
  src/erlang_types/ty_atom.erl
  src/erlang_types/ty_interval.erl
  src/erlang_types/ty_predef.erl
  src/erlang_types/ty_rec.erl
  src/erlang_types/ty_ref.erl
  src/erlang_types/ty_tuple.erl
  src/erlang_types/ty_variable.erl
  src/stdtypes.erl
Labels: Tally, Subtyping, architecture, soundness bug

#159 fix #157: consistent variable ordering
  src/ast_transform.erl
  test/ast_transform_test.erl
  test/pretty_test.erl
  test_files/ast_transform/tydef.erl
  test_files/ast_transform/tydef.out
Labels: bug
